export const mockProducts = [
  {
    id: "prod-1",
    productSlNo: 1,
    productSL: "BRT-8091",
    name: "Sony Alpha A7 IV Mirrorless Camera",
    pricePerDay: 450.0,
    pricePerHour: 65.0,
    productImages: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80",
    ],
    optimizedImages: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80",
    ],
    productType: "GADGET",
    productCondition: "LIKE_NEW",
    productAge: 5,
    omv: 240000,
    secondHandPrice: 195000,
    tags: "camera, sony, 4k, photography, mirrorless",
    productDescription:
      "Full-frame mirrorless camera with 33MP sensor, 4K 60p 10-bit video, and fast hybrid AF. Comes with 28-70mm kit lens and 2 batteries.",
    quantity: 1,
    ownerId: "owner-1",
    isAvailable: true,
    isForSaleOnly: false,
    isForSale: true,
    isAiEnabled: true,
    askingPrice: 195000,
    minPrice: 180000,
    scale: 1.0,
    isRented: false,
    isBrittooVerified: true,
    latitude: 24.3636,
    longitude: 88.6284,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    owner: {
      id: "owner-1",
      name: "Tanzim Hasan",
      email: "tanzim@ruet.ac.bd",
      roll: "1904001",
      securityScore: "VERY_HIGH",
      brittooVerified: true,
    },
  },
  {
    id: "prod-2",
    productSlNo: 2,
    productSL: "BRT-8092",
    name: "Yamaha FZ-S V3 (150cc)",
    pricePerDay: 800.0,
    pricePerHour: 120.0,
    productImages: [
      "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80",
    ],
    optimizedImages: [
      "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80",
    ],
    productType: "VEHICLE",
    productCondition: "GOOD",
    productAge: 14,
    omv: 255000,
    secondHandPrice: 185000,
    tags: "bike, yamaha, 150cc, fuel-efficient, commute",
    productDescription:
      "Smooth riding experience, Single channel ABS, regularly serviced. Helmet provided upon request.",
    quantity: 1,
    ownerId: "owner-2",
    isAvailable: true,
    isForSaleOnly: false,
    isForSale: false,
    isAiEnabled: false,
    scale: 1.0,
    isRented: false,
    isBrittooVerified: true,
    latitude: 24.368,
    longitude: 88.631,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    owner: {
      id: "owner-2",
      name: "Sabbir Ahmed",
      email: "sabbir@ruet.ac.bd",
      roll: "1903022",
      securityScore: "HIGH",
      brittooVerified: true,
    },
  },
  {
    id: "prod-3",
    productSlNo: 3,
    productSL: "BRT-8093",
    name: "MacBook Pro 14\" M2 Pro (16GB/512GB)",
    pricePerDay: 750.0,
    pricePerHour: 90.0,
    productImages: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
    ],
    optimizedImages: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
    ],
    productType: "ELECTRONICS",
    productCondition: "NEW",
    productAge: 2,
    omv: 210000,
    secondHandPrice: 175000,
    tags: "laptop, apple, macbook, m2, developer, programming",
    productDescription:
      "Superfast Apple Silicon M2 Pro chip, Liquid Retina XDR screen, 18-hour battery life. Ideal for coding, rendering, or design sprints.",
    quantity: 1,
    ownerId: "owner-3",
    isAvailable: true,
    isForSaleOnly: false,
    isForSale: true,
    isAiEnabled: true,
    askingPrice: 175000,
    minPrice: 165000,
    scale: 1.0,
    isRented: false,
    isBrittooVerified: true,
    latitude: 24.3615,
    longitude: 88.624,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    owner: {
      id: "owner-3",
      name: "Galib Asadullah",
      email: "galib@brittoo.com",
      roll: "1903000",
      securityScore: "VERY_HIGH",
      brittooVerified: true,
    },
  },
  {
    id: "prod-4",
    productSlNo: 4,
    productSL: "BRT-8094",
    name: "Fender Stratocaster Electric Guitar",
    pricePerDay: 250.0,
    pricePerHour: 40.0,
    productImages: [
      "https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?auto=format&fit=crop&w=800&q=80",
    ],
    optimizedImages: [
      "https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?auto=format&fit=crop&w=800&q=80",
    ],
    productType: "MUSICAL_INSTRUMENT",
    productCondition: "LIKE_NEW",
    productAge: 8,
    omv: 65000,
    secondHandPrice: 48000,
    tags: "guitar, music, electric, fender, stratocaster",
    productDescription:
      "Authentic Mexican Fender Stratocaster in sunburst finish. Low action, crisp tone, includes strap and padded gig bag.",
    quantity: 1,
    ownerId: "owner-1",
    isAvailable: true,
    isForSaleOnly: false,
    isForSale: true,
    isAiEnabled: false,
    askingPrice: 48000,
    minPrice: 42000,
    scale: 1.0,
    isRented: false,
    isBrittooVerified: true,
    latitude: 24.365,
    longitude: 88.629,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    owner: {
      id: "owner-1",
      name: "Tanzim Hasan",
      email: "tanzim@ruet.ac.bd",
      roll: "1904001",
      securityScore: "VERY_HIGH",
      brittooVerified: true,
    },
  },
  {
    id: "prod-5",
    productSlNo: 5,
    productSL: "BRT-8095",
    name: "DJI Mini 3 Pro Drone Combo",
    pricePerDay: 600.0,
    pricePerHour: 85.0,
    productImages: [
      "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=800&q=80",
    ],
    optimizedImages: [
      "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=800&q=80",
    ],
    productType: "GADGET",
    productCondition: "NEW",
    productAge: 3,
    omv: 95000,
    secondHandPrice: 78000,
    tags: "drone, dji, 4k, aerial, photography, video",
    productDescription:
      "Under 249g lightweight drone with 4K/60fps HDR video, tri-directional obstacle sensing, and 3 intelligent flight batteries (Fly More Kit).",
    quantity: 1,
    ownerId: "owner-2",
    isAvailable: true,
    isForSaleOnly: false,
    isForSale: true,
    isAiEnabled: true,
    askingPrice: 78000,
    minPrice: 72000,
    scale: 1.0,
    isRented: false,
    isBrittooVerified: true,
    latitude: 24.364,
    longitude: 88.625,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    owner: {
      id: "owner-2",
      name: "Sabbir Ahmed",
      email: "sabbir@ruet.ac.bd",
      roll: "1903022",
      securityScore: "HIGH",
      brittooVerified: true,
    },
  },
  {
    id: "prod-6",
    productSlNo: 6,
    productSL: "BRT-8096",
    name: "PlayStation 5 Console + 2 DualSense Controllers",
    pricePerDay: 350.0,
    pricePerHour: 50.0,
    productImages: [
      "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80",
    ],
    optimizedImages: [
      "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80",
    ],
    productType: "GADGET",
    productCondition: "LIKE_NEW",
    productAge: 9,
    omv: 68000,
    secondHandPrice: 52000,
    tags: "gaming, ps5, playstation, console, fifa, god-of-war",
    productDescription:
      "PlayStation 5 Disc Edition with 2 wireless controllers, HDMI 2.1 cable, and pre-installed games including EA FC 24 and Spider-Man 2.",
    quantity: 1,
    ownerId: "owner-3",
    isAvailable: true,
    isForSaleOnly: true,
    isForSale: true,
    isAiEnabled: true,
    askingPrice: 52000,
    minPrice: 48000,
    scale: 1.0,
    isRented: false,
    isBrittooVerified: true,
    latitude: 24.367,
    longitude: 88.627,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    owner: {
      id: "owner-3",
      name: "Galib Asadullah",
      email: "galib@brittoo.com",
      roll: "1903000",
      securityScore: "VERY_HIGH",
      brittooVerified: true,
    },
  },
  {
    id: "prod-7",
    productSlNo: 7,
    productSL: "BRT-8097",
    name: "Ergonomic Mesh Office Chair (High Back)",
    pricePerDay: 90.0,
    pricePerHour: 15.0,
    productImages: [
      "https://images.unsplash.com/photo-1580481077197-28d6c703b4eb?auto=format&fit=crop&w=800&q=80",
    ],
    optimizedImages: [
      "https://images.unsplash.com/photo-1580481077197-28d6c703b4eb?auto=format&fit=crop&w=800&q=80",
    ],
    productType: "FURNITURE",
    productCondition: "GOOD",
    productAge: 12,
    omv: 18000,
    secondHandPrice: 11000,
    tags: "chair, ergonomic, desk, office, furniture, posture",
    productDescription:
      "Breathable mesh back with adjustable lumbar support, 3D armrests, and 135-degree recline for long study and work sessions.",
    quantity: 2,
    ownerId: "owner-1",
    isAvailable: true,
    isForSaleOnly: false,
    isForSale: true,
    isAiEnabled: false,
    askingPrice: 11000,
    minPrice: 9500,
    scale: 1.0,
    isRented: false,
    isBrittooVerified: true,
    latitude: 24.362,
    longitude: 88.633,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    owner: {
      id: "owner-1",
      name: "Tanzim Hasan",
      email: "tanzim@ruet.ac.bd",
      roll: "1904001",
      securityScore: "VERY_HIGH",
      brittooVerified: true,
    },
  },
  {
    id: "prod-8",
    productSlNo: 8,
    productSL: "BRT-8098",
    name: "Introduction to Algorithms (CLRS 4th Edition)",
    pricePerDay: 30.0,
    pricePerHour: 5.0,
    productImages: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
    ],
    optimizedImages: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
    ],
    productType: "BOOK",
    productCondition: "LIKE_NEW",
    productAge: 4,
    omv: 3200,
    secondHandPrice: 2100,
    tags: "book, computer-science, algorithms, clrs, ruet, cse",
    productDescription:
      "Hardcover edition, flawless pages with zero pencil markings. The essential Bible for algorithms and data structures.",
    quantity: 1,
    ownerId: "owner-2",
    isAvailable: true,
    isForSaleOnly: false,
    isForSale: true,
    isAiEnabled: false,
    askingPrice: 2100,
    minPrice: 1800,
    scale: 1.0,
    isRented: false,
    isBrittooVerified: true,
    latitude: 24.3645,
    longitude: 88.628,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    owner: {
      id: "owner-2",
      name: "Sabbir Ahmed",
      email: "sabbir@ruet.ac.bd",
      roll: "1903022",
      securityScore: "HIGH",
      brittooVerified: true,
    },
  },
  {
    id: "prod-9",
    productSlNo: 9,
    productSL: "BRT-8099",
    name: "Bose QuietComfort 45 Wireless Headphones",
    pricePerDay: 200.0,
    pricePerHour: 30.0,
    productImages: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    ],
    optimizedImages: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    ],
    productType: "GADGET",
    productCondition: "LIKE_NEW",
    productAge: 6,
    omv: 36000,
    secondHandPrice: 26000,
    tags: "headphones, bose, noise-cancelling, bluetooth, audio",
    productDescription:
      "World-class active noise cancellation with Quiet and Aware modes, high-fidelity audio, and up to 24 hours battery on a single charge.",
    quantity: 1,
    ownerId: "owner-3",
    isAvailable: true,
    isForSaleOnly: false,
    isForSale: true,
    isAiEnabled: true,
    askingPrice: 26000,
    minPrice: 23000,
    scale: 1.0,
    isRented: false,
    isBrittooVerified: true,
    latitude: 24.366,
    longitude: 88.63,
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    owner: {
      id: "owner-3",
      name: "Galib Asadullah",
      email: "galib@brittoo.com",
      roll: "1903000",
      securityScore: "VERY_HIGH",
      brittooVerified: true,
    },
  },
  {
    id: "prod-10",
    productSlNo: 10,
    productSL: "BRT-8100",
    name: "Trek Marlin 7 Mountain Bicycle",
    pricePerDay: 280.0,
    pricePerHour: 45.0,
    productImages: [
      "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80",
    ],
    optimizedImages: [
      "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80",
    ],
    productType: "VEHICLE",
    productCondition: "GOOD",
    productAge: 10,
    omv: 62000,
    secondHandPrice: 42000,
    tags: "bicycle, cycle, trek, mountain-bike, mtb, fitness",
    productDescription:
      "Hydraulic disc brakes, RockShox suspension fork with lockout, 1x10 Shimano Deore drivetrain. Perfect for campus and off-road trail rides.",
    quantity: 1,
    ownerId: "owner-1",
    isAvailable: true,
    isForSaleOnly: false,
    isForSale: true,
    isAiEnabled: false,
    askingPrice: 42000,
    minPrice: 38000,
    scale: 1.0,
    isRented: false,
    isBrittooVerified: true,
    latitude: 24.363,
    longitude: 88.626,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    owner: {
      id: "owner-1",
      name: "Tanzim Hasan",
      email: "tanzim@ruet.ac.bd",
      roll: "1904001",
      securityScore: "VERY_HIGH",
      brittooVerified: true,
    },
  },
  {
    id: "prod-11",
    productSlNo: 11,
    productSL: "BRT-8101",
    name: "BenQ 4K HDR Home Cinema Projector",
    pricePerDay: 400.0,
    pricePerHour: 60.0,
    productImages: [
      "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80",
    ],
    optimizedImages: [
      "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80",
    ],
    productType: "ELECTRONICS",
    productCondition: "LIKE_NEW",
    productAge: 7,
    omv: 115000,
    secondHandPrice: 85000,
    tags: "projector, 4k, movie-night, cinema, benq, presentation",
    productDescription:
      "True 4K UHD 8.3 million pixels resolution with CinematicColor technology. Great for movie nights, gaming, and project presentations.",
    quantity: 1,
    ownerId: "owner-2",
    isAvailable: true,
    isForSaleOnly: false,
    isForSale: true,
    isAiEnabled: true,
    askingPrice: 85000,
    minPrice: 78000,
    scale: 1.0,
    isRented: false,
    isBrittooVerified: true,
    latitude: 24.3655,
    longitude: 88.6285,
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    owner: {
      id: "owner-2",
      name: "Sabbir Ahmed",
      email: "sabbir@ruet.ac.bd",
      roll: "1903022",
      securityScore: "HIGH",
      brittooVerified: true,
    },
  },
  {
    id: "prod-12",
    productSlNo: 12,
    productSL: "BRT-8102",
    name: "Wacom Cintiq 16 Drawing Tablet",
    pricePerDay: 300.0,
    pricePerHour: 45.0,
    productImages: [
      "https://images.unsplash.com/photo-1563206767-5b18f218e8de?auto=format&fit=crop&w=800&q=80",
    ],
    optimizedImages: [
      "https://images.unsplash.com/photo-1563206767-5b18f218e8de?auto=format&fit=crop&w=800&q=80",
    ],
    productType: "GADGET",
    productCondition: "GOOD",
    productAge: 11,
    omv: 78000,
    secondHandPrice: 54000,
    tags: "wacom, tablet, drawing, design, illustration, art",
    productDescription:
      "15.6 inch 1920x1080 Full HD display with Pro Pen 2 offering 8,192 levels of pressure sensitivity. Includes stand and all cables.",
    quantity: 1,
    ownerId: "owner-3",
    isAvailable: true,
    isForSaleOnly: false,
    isForSale: true,
    isAiEnabled: false,
    askingPrice: 54000,
    minPrice: 49000,
    scale: 1.0,
    isRented: false,
    isBrittooVerified: true,
    latitude: 24.3625,
    longitude: 88.6295,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    owner: {
      id: "owner-3",
      name: "Galib Asadullah",
      email: "galib@brittoo.com",
      roll: "1903000",
      securityScore: "VERY_HIGH",
      brittooVerified: true,
    },
  },
];

export const mockNotifications = [
  {
    id: "notif-1",
    title: "Welcome to Brittoo! 🎉",
    message: "Discover and share gadgets, vehicles, books, and tools seamlessly within your community.",
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif-2",
    title: "Credits Active 💳",
    message: "You have 1,250 Blue Cash Credits available to rent any gear of your choice.",
    isRead: false,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
];
