name: "Brittoo"

services:

  britto-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src:ro
      - /app/node_modules


  britto-server:
    build:
      context: ./server
      args:
        - NODE_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app:ro
      - /app/node_modules
    env_file:
      - ./server/.env
    command: npm run dev

  db:
    image: postgres
    environment:
      - POSTGRES_USER=galib
      - POSTGRES_PASSWORD=galib2010033
      - POSTGRES_DB=brittoodb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    
    ## VISIT DB Locally: psql -h localhost -p 5433 -U galib -d brittoodb



volumes:
  pgdata:


# ===========================================
# DEV COMMANDS (using docker-compose-dev.yml)
# ===========================================

#   --Up (start in detached mode):
#       $ docker compose -f docker-compose-dev.yml up -d

#   --List images (confirm image is built):
#       $ docker image ls

#   --Down & Delete anonymous volumes:
#       $ docker compose -f docker-compose-dev.yml down -v

#   --Force rebuild from scratch (no cache):
#       $ docker compose -f docker-compose-dev.yml up -d --build



